### ISSUE TITLE
【警告】日本マスターズ水泳協会

### ISSUE THREAD

**Issue by JMSA-admin** [supercaracal/japan-masters-swimming#12]
管理者の方へ
本サイトについて至急閉鎖をするよう要請します。
サイトには「Sourced by Japan Masters Swimming Association」と記載されていますが、当協会が許諾した経緯はありません。
また、貴方がこれら各個人の情報を公開する権利を各々より得ていない場合は、当該個人より賠償または何らかの法的措置を取られる場合があることをご理解しておいてください。
2018年2月15日　日本マスターズ水泳協会事務局

**Comment by supercaracal** [comment]
すみません、閉鎖いたしました。以後気を付けます。

**Comment by JMSA-admin** [comment]
確認しました。データの取り扱いには十分注意するようお願いします。

**Comment by supercaracal** [comment]
承知いたしました。勉強になりました。
